import type { Metadata } from 'next';
import { Noto_Sans, Inter } from 'next/font/google';

import './globals.css';
import React from 'react';

const noto_Sans = Noto_Sans({
  variable: '--noto-sans-font',
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  fallback: ['sans-serif'],
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  preload: true,
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--inter-font',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Наш проект',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={`${inter.variable} ${noto_Sans.className}`}>{children}</body>
    </html>
  );
}
